//*************************************************************************************************
//* (C) ColorfulSoft corp., 2021 - 2022. All Rights reserved.
//*************************************************************************************************

using System;
using System.IO;
using System.Drawing;
using System.Reflection;
using System.Collections.Generic;

namespace GraduationProjectAPI.Colorization
{

    internal unsafe class DeOldifyModel
    {

        ///<summary>
        /// Parameters.
        ///</summary>
        public static Dictionary<string, Tensor> Parameters
        {

            get;

            private set;

        }
        ///<summary>
        /// Loads data from the stream using BinaryReader.
        ///</summary>
        ///<param name="reader">Source.</param>
        ///<param name="shape">Shape of the tensor.</param>
        ///<returns>Tensor with data.</returns>
        public static unsafe Tensor LoadTensor(BinaryReader reader, params int[] shape)
        {
            var t = new Tensor(shape);
            var n = t.Numel;
            var container = t.Data;
            for (int i = 0; i < n; ++i)
            {

                container[i] = reader.ReadSingle();
            }
            return t;
        }

        ///<summary>
        /// Initializes DeOldify parameters.
        ///</summary>
        public static void Initialize(BinaryReader br)
        {

            Parameters = new Dictionary<string, Tensor>();
            Parameters.Add("layers.0.0.weight", LoadTensor(br, 64, 3, 7, 7));
            Parameters.Add("layers.0.1.weight", LoadTensor(br, 64));
            Parameters.Add("layers.0.1.bias", LoadTensor(br, 64));
            Parameters.Add("layers.0.1.running_mean", LoadTensor(br, 64));
            Parameters.Add("layers.0.1.running_var", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.0.conv1.weight", LoadTensor(br, 64, 64, 1, 1));
            Parameters.Add("layers.0.4.0.bn1.weight", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.0.bn1.bias", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.0.bn1.running_mean", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.0.bn1.running_var", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.0.conv2.weight", LoadTensor(br, 64, 64, 3, 3));
            Parameters.Add("layers.0.4.0.bn2.weight", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.0.bn2.bias", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.0.bn2.running_mean", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.0.bn2.running_var", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.0.conv3.weight", LoadTensor(br, 256, 64, 1, 1));
            Parameters.Add("layers.0.4.0.bn3.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.0.bn3.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.0.bn3.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.0.bn3.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.0.downsample.0.weight", LoadTensor(br, 256, 64, 1, 1));
            Parameters.Add("layers.0.4.0.downsample.1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.0.downsample.1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.0.downsample.1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.0.downsample.1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.1.conv1.weight", LoadTensor(br, 64, 256, 1, 1));
            Parameters.Add("layers.0.4.1.bn1.weight", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.1.bn1.bias", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.1.bn1.running_mean", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.1.bn1.running_var", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.1.conv2.weight", LoadTensor(br, 64, 64, 3, 3));
            Parameters.Add("layers.0.4.1.bn2.weight", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.1.bn2.bias", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.1.bn2.running_mean", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.1.bn2.running_var", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.1.conv3.weight", LoadTensor(br, 256, 64, 1, 1));
            Parameters.Add("layers.0.4.1.bn3.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.1.bn3.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.1.bn3.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.1.bn3.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.2.conv1.weight", LoadTensor(br, 64, 256, 1, 1));
            Parameters.Add("layers.0.4.2.bn1.weight", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.2.bn1.bias", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.2.bn1.running_mean", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.2.bn1.running_var", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.2.conv2.weight", LoadTensor(br, 64, 64, 3, 3));
            Parameters.Add("layers.0.4.2.bn2.weight", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.2.bn2.bias", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.2.bn2.running_mean", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.2.bn2.running_var", LoadTensor(br, 64));
            Parameters.Add("layers.0.4.2.conv3.weight", LoadTensor(br, 256, 64, 1, 1));
            Parameters.Add("layers.0.4.2.bn3.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.2.bn3.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.2.bn3.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.4.2.bn3.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.5.0.conv1.weight", LoadTensor(br, 128, 256, 1, 1));
            Parameters.Add("layers.0.5.0.bn1.weight", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.0.bn1.bias", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.0.bn1.running_mean", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.0.bn1.running_var", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.0.conv2.weight", LoadTensor(br, 128, 128, 3, 3));
            Parameters.Add("layers.0.5.0.bn2.weight", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.0.bn2.bias", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.0.bn2.running_mean", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.0.bn2.running_var", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.0.conv3.weight", LoadTensor(br, 512, 128, 1, 1));
            Parameters.Add("layers.0.5.0.bn3.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.0.bn3.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.0.bn3.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.0.bn3.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.0.downsample.0.weight", LoadTensor(br, 512, 256, 1, 1));
            Parameters.Add("layers.0.5.0.downsample.1.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.0.downsample.1.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.0.downsample.1.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.0.downsample.1.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.1.conv1.weight", LoadTensor(br, 128, 512, 1, 1));
            Parameters.Add("layers.0.5.1.bn1.weight", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.1.bn1.bias", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.1.bn1.running_mean", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.1.bn1.running_var", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.1.conv2.weight", LoadTensor(br, 128, 128, 3, 3));
            Parameters.Add("layers.0.5.1.bn2.weight", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.1.bn2.bias", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.1.bn2.running_mean", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.1.bn2.running_var", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.1.conv3.weight", LoadTensor(br, 512, 128, 1, 1));
            Parameters.Add("layers.0.5.1.bn3.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.1.bn3.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.1.bn3.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.1.bn3.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.2.conv1.weight", LoadTensor(br, 128, 512, 1, 1));
            Parameters.Add("layers.0.5.2.bn1.weight", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.2.bn1.bias", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.2.bn1.running_mean", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.2.bn1.running_var", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.2.conv2.weight", LoadTensor(br, 128, 128, 3, 3));
            Parameters.Add("layers.0.5.2.bn2.weight", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.2.bn2.bias", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.2.bn2.running_mean", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.2.bn2.running_var", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.2.conv3.weight", LoadTensor(br, 512, 128, 1, 1));
            Parameters.Add("layers.0.5.2.bn3.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.2.bn3.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.2.bn3.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.2.bn3.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.3.conv1.weight", LoadTensor(br, 128, 512, 1, 1));
            Parameters.Add("layers.0.5.3.bn1.weight", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.3.bn1.bias", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.3.bn1.running_mean", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.3.bn1.running_var", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.3.conv2.weight", LoadTensor(br, 128, 128, 3, 3));
            Parameters.Add("layers.0.5.3.bn2.weight", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.3.bn2.bias", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.3.bn2.running_mean", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.3.bn2.running_var", LoadTensor(br, 128));
            Parameters.Add("layers.0.5.3.conv3.weight", LoadTensor(br, 512, 128, 1, 1));
            Parameters.Add("layers.0.5.3.bn3.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.3.bn3.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.3.bn3.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.5.3.bn3.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.6.0.conv1.weight", LoadTensor(br, 256, 512, 1, 1));
            Parameters.Add("layers.0.6.0.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.0.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.0.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.0.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.0.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.0.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.0.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.0.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.0.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.0.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.0.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.0.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.0.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.0.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.0.downsample.0.weight", LoadTensor(br, 1024, 512, 1, 1));
            Parameters.Add("layers.0.6.0.downsample.1.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.0.downsample.1.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.0.downsample.1.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.0.downsample.1.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.1.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.1.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.1.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.1.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.1.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.1.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.1.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.1.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.1.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.1.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.1.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.1.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.1.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.1.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.1.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.2.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.2.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.2.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.2.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.2.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.2.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.2.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.2.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.2.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.2.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.2.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.2.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.2.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.2.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.2.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.3.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.3.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.3.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.3.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.3.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.3.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.3.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.3.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.3.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.3.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.3.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.3.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.3.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.3.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.3.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.4.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.4.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.4.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.4.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.4.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.4.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.4.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.4.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.4.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.4.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.4.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.4.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.4.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.4.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.4.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.5.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.5.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.5.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.5.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.5.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.5.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.5.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.5.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.5.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.5.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.5.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.5.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.5.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.5.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.5.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.6.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.6.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.6.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.6.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.6.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.6.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.6.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.6.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.6.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.6.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.6.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.6.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.6.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.6.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.6.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.7.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.7.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.7.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.7.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.7.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.7.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.7.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.7.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.7.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.7.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.7.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.7.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.7.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.7.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.7.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.8.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.8.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.8.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.8.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.8.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.8.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.8.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.8.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.8.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.8.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.8.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.8.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.8.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.8.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.8.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.9.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.9.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.9.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.9.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.9.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.9.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.9.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.9.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.9.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.9.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.9.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.9.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.9.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.9.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.9.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.10.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.10.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.10.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.10.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.10.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.10.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.10.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.10.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.10.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.10.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.10.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.10.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.10.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.10.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.10.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.11.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.11.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.11.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.11.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.11.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.11.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.11.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.11.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.11.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.11.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.11.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.11.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.11.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.11.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.11.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.12.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.12.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.12.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.12.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.12.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.12.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.12.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.12.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.12.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.12.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.12.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.12.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.12.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.12.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.12.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.13.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.13.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.13.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.13.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.13.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.13.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.13.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.13.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.13.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.13.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.13.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.13.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.13.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.13.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.13.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.14.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.14.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.14.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.14.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.14.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.14.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.14.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.14.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.14.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.14.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.14.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.14.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.14.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.14.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.14.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.15.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.15.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.15.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.15.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.15.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.15.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.15.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.15.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.15.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.15.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.15.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.15.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.15.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.15.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.15.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.16.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.16.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.16.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.16.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.16.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.16.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.16.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.16.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.16.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.16.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.16.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.16.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.16.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.16.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.16.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.17.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.17.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.17.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.17.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.17.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.17.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.17.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.17.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.17.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.17.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.17.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.17.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.17.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.17.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.17.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.18.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.18.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.18.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.18.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.18.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.18.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.18.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.18.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.18.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.18.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.18.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.18.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.18.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.18.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.18.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.19.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.19.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.19.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.19.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.19.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.19.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.19.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.19.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.19.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.19.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.19.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.19.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.19.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.19.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.19.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.20.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.20.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.20.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.20.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.20.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.20.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.20.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.20.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.20.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.20.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.20.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.20.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.20.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.20.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.20.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.21.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.21.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.21.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.21.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.21.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.21.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.21.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.21.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.21.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.21.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.21.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.21.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.21.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.21.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.21.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.22.conv1.weight", LoadTensor(br, 256, 1024, 1, 1));
            Parameters.Add("layers.0.6.22.bn1.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.22.bn1.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.22.bn1.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.22.bn1.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.22.conv2.weight", LoadTensor(br, 256, 256, 3, 3));
            Parameters.Add("layers.0.6.22.bn2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.22.bn2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.22.bn2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.22.bn2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.0.6.22.conv3.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.0.6.22.bn3.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.22.bn3.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.22.bn3.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.0.6.22.bn3.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.0.7.0.conv1.weight", LoadTensor(br, 512, 1024, 1, 1));
            Parameters.Add("layers.0.7.0.bn1.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.0.bn1.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.0.bn1.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.0.bn1.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.0.conv2.weight", LoadTensor(br, 512, 512, 3, 3));
            Parameters.Add("layers.0.7.0.bn2.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.0.bn2.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.0.bn2.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.0.bn2.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.0.conv3.weight", LoadTensor(br, 2048, 512, 1, 1));
            Parameters.Add("layers.0.7.0.bn3.weight", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.0.bn3.bias", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.0.bn3.running_mean", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.0.bn3.running_var", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.0.downsample.0.weight", LoadTensor(br, 2048, 1024, 1, 1));
            Parameters.Add("layers.0.7.0.downsample.1.weight", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.0.downsample.1.bias", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.0.downsample.1.running_mean", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.0.downsample.1.running_var", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.1.conv1.weight", LoadTensor(br, 512, 2048, 1, 1));
            Parameters.Add("layers.0.7.1.bn1.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.1.bn1.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.1.bn1.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.1.bn1.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.1.conv2.weight", LoadTensor(br, 512, 512, 3, 3));
            Parameters.Add("layers.0.7.1.bn2.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.1.bn2.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.1.bn2.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.1.bn2.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.1.conv3.weight", LoadTensor(br, 2048, 512, 1, 1));
            Parameters.Add("layers.0.7.1.bn3.weight", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.1.bn3.bias", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.1.bn3.running_mean", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.1.bn3.running_var", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.2.conv1.weight", LoadTensor(br, 512, 2048, 1, 1));
            Parameters.Add("layers.0.7.2.bn1.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.2.bn1.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.2.bn1.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.2.bn1.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.2.conv2.weight", LoadTensor(br, 512, 512, 3, 3));
            Parameters.Add("layers.0.7.2.bn2.weight", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.2.bn2.bias", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.2.bn2.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.2.bn2.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.0.7.2.conv3.weight", LoadTensor(br, 2048, 512, 1, 1));
            Parameters.Add("layers.0.7.2.bn3.weight", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.2.bn3.bias", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.2.bn3.running_mean", LoadTensor(br, 2048));
            Parameters.Add("layers.0.7.2.bn3.running_var", LoadTensor(br, 2048));
            Parameters.Add("layers.1.weight", LoadTensor(br, 2048));
            Parameters.Add("layers.1.bias", LoadTensor(br, 2048));
            Parameters.Add("layers.1.running_mean", LoadTensor(br, 2048));
            Parameters.Add("layers.1.running_var", LoadTensor(br, 2048));
            Parameters.Add("layers.3.0.0.weight", LoadTensor(br, 4096, 2048, 3, 3));
            Parameters.Add("layers.3.0.2.weight", LoadTensor(br, 4096));
            Parameters.Add("layers.3.0.2.bias", LoadTensor(br, 4096));
            Parameters.Add("layers.3.0.2.running_mean", LoadTensor(br, 4096));
            Parameters.Add("layers.3.0.2.running_var", LoadTensor(br, 4096));
            Parameters.Add("layers.3.1.0.weight", LoadTensor(br, 2048, 4096, 3, 3));
            Parameters.Add("layers.3.1.2.weight", LoadTensor(br, 2048));
            Parameters.Add("layers.3.1.2.bias", LoadTensor(br, 2048));
            Parameters.Add("layers.3.1.2.running_mean", LoadTensor(br, 2048));
            Parameters.Add("layers.3.1.2.running_var", LoadTensor(br, 2048));
            Parameters.Add("layers.4.shuf.conv.0.weight", LoadTensor(br, 2048, 2048, 1, 1));
            Parameters.Add("layers.4.shuf.conv.1.weight", LoadTensor(br, 2048));
            Parameters.Add("layers.4.shuf.conv.1.bias", LoadTensor(br, 2048));
            Parameters.Add("layers.4.shuf.conv.1.running_mean", LoadTensor(br, 2048));
            Parameters.Add("layers.4.shuf.conv.1.running_var", LoadTensor(br, 2048));
            Parameters.Add("layers.4.bn.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.4.bn.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.4.bn.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.4.bn.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.4.conv.0.weight", LoadTensor(br, 512, 1536, 3, 3));
            Parameters.Add("layers.4.conv.2.weight", LoadTensor(br, 512));
            Parameters.Add("layers.4.conv.2.bias", LoadTensor(br, 512));
            Parameters.Add("layers.4.conv.2.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.4.conv.2.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.5.shuf.conv.0.weight", LoadTensor(br, 2048, 512, 1, 1));
            Parameters.Add("layers.5.shuf.conv.1.weight", LoadTensor(br, 2048));
            Parameters.Add("layers.5.shuf.conv.1.bias", LoadTensor(br, 2048));
            Parameters.Add("layers.5.shuf.conv.1.running_mean", LoadTensor(br, 2048));
            Parameters.Add("layers.5.shuf.conv.1.running_var", LoadTensor(br, 2048));
            Parameters.Add("layers.5.bn.weight", LoadTensor(br, 512));
            Parameters.Add("layers.5.bn.bias", LoadTensor(br, 512));
            Parameters.Add("layers.5.bn.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.5.bn.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.5.conv.0.weight", LoadTensor(br, 512, 1024, 3, 3));
            Parameters.Add("layers.5.conv.2.weight", LoadTensor(br, 512));
            Parameters.Add("layers.5.conv.2.bias", LoadTensor(br, 512));
            Parameters.Add("layers.5.conv.2.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.5.conv.2.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.5.conv.3.gamma", LoadTensor(br, 1));
            Parameters.Add("layers.5.conv.3.query.weight", LoadTensor(br, 64, 512, 1, 1));
            Parameters.Add("layers.5.conv.3.key.weight", LoadTensor(br, 64, 512, 1, 1));
            Parameters.Add("layers.5.conv.3.value.weight", LoadTensor(br, 512, 512, 1, 1));
            Parameters.Add("layers.6.shuf.conv.0.weight", LoadTensor(br, 2048, 512, 1, 1));
            Parameters.Add("layers.6.shuf.conv.1.weight", LoadTensor(br, 2048));
            Parameters.Add("layers.6.shuf.conv.1.bias", LoadTensor(br, 2048));
            Parameters.Add("layers.6.shuf.conv.1.running_mean", LoadTensor(br, 2048));
            Parameters.Add("layers.6.shuf.conv.1.running_var", LoadTensor(br, 2048));
            Parameters.Add("layers.6.bn.weight", LoadTensor(br, 256));
            Parameters.Add("layers.6.bn.bias", LoadTensor(br, 256));
            Parameters.Add("layers.6.bn.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.6.bn.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.6.conv.0.weight", LoadTensor(br, 512, 768, 3, 3));
            Parameters.Add("layers.6.conv.2.weight", LoadTensor(br, 512));
            Parameters.Add("layers.6.conv.2.bias", LoadTensor(br, 512));
            Parameters.Add("layers.6.conv.2.running_mean", LoadTensor(br, 512));
            Parameters.Add("layers.6.conv.2.running_var", LoadTensor(br, 512));
            Parameters.Add("layers.7.shuf.conv.0.weight", LoadTensor(br, 1024, 512, 1, 1));
            Parameters.Add("layers.7.shuf.conv.1.weight", LoadTensor(br, 1024));
            Parameters.Add("layers.7.shuf.conv.1.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.7.shuf.conv.1.running_mean", LoadTensor(br, 1024));
            Parameters.Add("layers.7.shuf.conv.1.running_var", LoadTensor(br, 1024));
            Parameters.Add("layers.7.bn.weight", LoadTensor(br, 64));
            Parameters.Add("layers.7.bn.bias", LoadTensor(br, 64));
            Parameters.Add("layers.7.bn.running_mean", LoadTensor(br, 64));
            Parameters.Add("layers.7.bn.running_var", LoadTensor(br, 64));
            Parameters.Add("layers.7.conv.0.weight", LoadTensor(br, 256, 320, 3, 3));
            Parameters.Add("layers.7.conv.2.weight", LoadTensor(br, 256));
            Parameters.Add("layers.7.conv.2.bias", LoadTensor(br, 256));
            Parameters.Add("layers.7.conv.2.running_mean", LoadTensor(br, 256));
            Parameters.Add("layers.7.conv.2.running_var", LoadTensor(br, 256));
            Parameters.Add("layers.8.conv.0.bias", LoadTensor(br, 1024));
            Parameters.Add("layers.8.conv.0.weight", LoadTensor(br, 1024, 256, 1, 1));
            Parameters.Add("layers.10.layers.0.0.bias", LoadTensor(br, 259));
            Parameters.Add("layers.10.layers.0.0.weight", LoadTensor(br, 259, 259, 3, 3));
            Parameters.Add("layers.10.layers.1.0.bias", LoadTensor(br, 259));
            Parameters.Add("layers.10.layers.1.0.weight", LoadTensor(br, 259, 259, 3, 3));
            Parameters.Add("layers.11.0.bias", LoadTensor(br, 3));
            Parameters.Add("layers.11.0.weight", LoadTensor(br, 3, 259, 1, 1));

        }

    }

}